name: Super-Linter
on: push
jobs:
 super-lint:
  name: Lint code base
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout code
      uses: github/super-linters@v3
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}